name: 'Open Next PR'
description: 'Open PRs depending on other PRs automatically.'
author: 'realglobe, Inc.'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
