name: "Release Next PR"
description: "Handles serial pull requests"
author: "realglobe, Inc."
inputs:
  github-token:
    description: "GitHub Token"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
