name: 'Release Next PR'
description: 'Release PRs depending on the merged PR automatically.'
author: 'realglobe, Inc.'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
