name: 'Open Next PR'
description: 'Open PRs depending on other PRs automatically.'
author: 'realglobe, Inc.'
inputs:
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
